### ISSUE TITLE
SyntaxError

### ISSUE THREAD

**Issue by rkneer** [askmike/deribit-v2-ws#17]
Hi Mike,

First off, I'm somewhat of a JS noob.

I'm encountering a syntax error when I run your example code:

```
handleError = (e) => {

SyntaxError: Unexpected token =
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:616:28)
    at Module._compile (/home/ryan/code/logos/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (module.js:663:10)
    at Object.newLoader [as .js] (/home/ryan/code/logos/node_modules/pirates/lib/index.js:104:7)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Module.require (module.js:596:17)
```

I use this syntax throughout my codebase, so I'm quite perplexed at the moment.

I tried rewriting the declaration like:

`handleError(e) {`

Which enabled the code to run, but it would then throw:

>     const request = this.findRequest(payload.id);
>                          ^
> TypeError: this.findRequest is not a function

I'm sure I'm operating with some basic misunderstanding of JS syntax here.

In the first error block, I see reference made to a module named 'pirates', which I see makes reference to Babel. Is Babel needed to compile this package?

**Comment by lacksfish** [comment]
Which version of nodejs are you using?

Possibly, could you provide a minimal code snippet reproducing this error?

**Comment by rkneer** [comment]
Node v8.10.0

If I run this:
```
const key = config.apikey
const secret = config.secret
const Deribit = require('deribit-v2-ws')
const db = new Deribit({key, secret})
const position = await db.request(
  'private/get_position',
  {instrument_name: 'BTC-PERPETUAL'}
)
console.log(position)
```
I get:

```
const position = await db.request(
                 ^^^^^

SyntaxError: await is only valid in async function
```

I suppose installing Babel would resolve that issue (I haven't learned it yet).

However, when I rewrite the code using my regular 'then' syntax:
```
const key = config.apikey
const secret = config.secret
const Deribit = require('deribit-v2-ws')
const db = new Deribit({key, secret})
db.request(
  'private/get_position',
  {instrument_name: 'BTC-PERPETUAL'}
).then( res => {
  console.log(res)
})
```
It throws:
```
  handleError = (e) => {
              ^

SyntaxError: Unexpected token =
```
Which leads me think it's something to do with my compiler.

**Comment by lacksfish** [comment]
Ok firstly, it seems youre not calling `await db.connect();` anywhere.

I think you're looking for something like this

```
(async () => {
	const key = null
	const secret = null
	const Deribit = require('deribit-v2-ws')
	const db = new Deribit({key, secret})

	await db.connect()

	db.request(
	  'public/get_index',
	  {currency: 'BTC'}
	).then( res => {
	  console.log(res)

	})
})();

```

**Comment by lacksfish** [comment]
Actually yes @askmike maybe the README example should include the `connect()` call, as it is mandatory.

**Comment by rkneer** [comment]
Upgraded my Node installation, included the `connect()` call, and now it works. Thank you :)

**Comment by askmike** [comment]
Great! I now added the `connect()` call to the example in the readme.
