### ISSUE TITLE
Not working in Browser

### ISSUE THREAD

**Issue by Quenos** [askmike/deribit-v2-ws#18]
I'm getting the following error in the console.

Uncaught (in promise) Error: ws does not work in the browser. Browser clients must use the native WebSocket object

**Comment by lacksfish** [comment]
Hopefully this answers your question

https://stackoverflow.com/questions/29741158/how-to-use-websocket-npm-library-in-browser

You mightn't be able to run this in the browser without some modifications, or figuring out a way to browserify this library.

**Comment by Quenos** [comment]
I uncommented the require of 'ws' and it works when I comment line 60 out in connection.js (this.ws.on) because that line throws some kind of an exception it seems

**Comment by lacksfish** [comment]
Which exception? Got the error log for that?

It does make sense uncommenting the require of 'ws'. Browsers have a native implementation of the WebSocket class. But your initial error told you that already ;)

**Comment by Quenos** [comment]
connection.js?ea94:60 Uncaught (in promise) TypeError: _this2.ws.on is not a function
    at eval (connection.js?ea94:60)
    at new Promise (<anonymous>)
    at Connection._connect (connection.js?ea94:46)
    at _callee4$ (connection.js?ea94:122)
    at tryCatch (runtime.js?96cf:45)
    at Generator.invoke [as _invoke] (runtime.js?96cf:274)
    at Generator.prototype.<computed> [as next] (runtime.js?96cf:97)
    at asyncGeneratorStep (asyncToGenerator.js?c973:3)
    at _next (asyncToGenerator.js?c973:25)
    at eval (asyncToGenerator.js?c973:32)
eval @ connection.js?ea94:60
_connect @ connection.js?ea94:46
_callee4$ @ connection.js?ea94:122
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?c973:3
_next @ asyncToGenerator.js?c973:25
eval @ asyncToGenerator.js?c973:32
eval @ asyncToGenerator.js?c973:21
_callee$ @ Deribit.js?4cc9:14
tryCatch @ runtime.js?96cf:45
invoke @ runtime.js?96cf:274
prototype.<computed> @ runtime.js?96cf:97
asyncGeneratorStep @ asyncToGenerator.js?1da1:3
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
getPositions @ Deribit.js?4cc9:14
Positions @ Ladder.vue?041a:125
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
Vue.$emit @ vue.runtime.esm.js?2b0e:3888
click @ VBtn.ts?0eff:158
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
Promise.then (async)
asyncGeneratorStep @ asyncToGenerator.js?1da1:13
_next @ asyncToGenerator.js?1da1:25
eval @ asyncToGenerator.js?1da1:32
eval @ asyncToGenerator.js?1da1:21
getPositions @ Deribit.js?4cc9:14
Positions @ Ladder.vue?041a:125
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
```
Vue.$emit @ vue.runtime.esm.js?2b0e:3888
click @ VBtn.ts?0eff:158
invokeWithErrorHandling @ vue.runtime.esm.js?2b0e:1854
invoker @ vue.runtime.esm.js?2b0e:2179
original._wrapper @ vue.runtime.esm.js?2b0e:6917
```

**Comment by lacksfish** [comment]
You sure you're not doing something that is maleating the code (browserify/webpack/rollup)? It sure does look like it. If so, don't rely on the error code line number too much, it might be off by a bit.

Since the call error is referencing `.on()` could it actually be https://github.com/askmike/deribit-v2-ws/blob/3a350198b514b4daa1839bc74fa5c26525d3f35f/connection.js#L58 this line?

idk I'm just guessing.

**Comment by Quenos** [comment]
Nothing that I'm aware of... but maybe.

The line number is ok, because if I remove 
` this.ws.on('error', `this.handleError)` 
then it works perfectly

**Comment by lacksfish** [comment]
Well, great! That's line 58 thought, not 60 like you said. :)

It seems to be an issue with the native browser WebSocket class.

Anyways, @askmike is there a reasoning why the error handler function is getting registered two different ways in the first place?

I see

https://github.com/askmike/deribit-v2-ws/blob/3a350198b514b4daa1839bc74fa5c26525d3f35f/connection.js#L57

And in the next line I see

https://github.com/askmike/deribit-v2-ws/blob/3a350198b514b4daa1839bc74fa5c26525d3f35f/connection.js#L58

Maybe the first one should do the trick anyways? ^^°

**Comment by Quenos** [comment]
In my file it's line 60, but maybe prettier did some reformatting. :)

Thanks for your your quick responses. Really appreciated!

**Comment by askmike** [comment]
@lacksfish 

> Anyways, @askmike is there a reasoning why the error handler function is getting registered two different ways in the first place?

No good reason, just legacy. Can be cleaned up if anyone cares.

@Quenos this library is not designed for browser use. It might work in some browsers after flipping a few things (like the ws lib), but overall I can't really guarantee it will keep working. I (and many) use this lib in the backend in nodejs for trading.

**Comment by lacksfish** [comment]
> No good reason, just legacy. Can be cleaned up if anyone cares.

Will do :)
